version: '3.4'

volumes:
  datafiles:

services:
  database:
    build: ./Database
    environment:
      SA_PASSWORD: "Rootpas$"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Rootpas$" -Q "SELECT 1" -b
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  stackoverflowtags.api:
    image: ${DOCKER_REGISTRY-}stackoverflowtagsapi
    build:
      context: .
      dockerfile: StackOverflowTagsAPI/Dockerfile
    ports:
    - "5000:5000"
    - "5001:5001" 
    environment:
    - DBHOST=database
    depends_on:
      database:
        condition: service_healthy
    restart: always
